// <auto-generated />
namespace WpfApp5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class in11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(in11));
        
        string IMigrationMetadata.Id
        {
            get { return "202405141826213_in11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
