// <auto-generated />
namespace WpfApp5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class in13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(in13));
        
        string IMigrationMetadata.Id
        {
            get { return "202405142022150_in13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
